// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenueHosting.Module.Attendee.Infrastructure.Persistence;

#nullable disable

namespace VenueHosting.Module.Attendee.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AttendeeApplicationDbContext))]
    partial class AttendeeApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Attendee")
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VenueHosting.Module.Attendee.Domain.Attendee.Attendee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Attendees", "Attendee");
                });

            modelBuilder.Entity("VenueHosting.Module.Attendee.Domain.AttendeeReview.AttendeeReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttendeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Comment");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDateTime");

                    b.Property<float>("RatingGiven")
                        .HasColumnType("real")
                        .HasColumnName("RatingGiven");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AttendeeReviews", "Attendee");
                });

            modelBuilder.Entity("VenueHosting.Module.Attendee.Domain.Attendee.Attendee", b =>
                {
                    b.OwnsMany("VenueHosting.Module.Attendee.Domain.Attendee.ValueObjects.BillId", "BillIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AttendeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Id");

                            b1.HasKey("Id");

                            b1.HasIndex("AttendeeId");

                            b1.ToTable("AttendeeBillIds", "Attendee", t =>
                                {
                                    t.Property("Id")
                                        .HasColumnName("Id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("AttendeeId");
                        });

                    b.OwnsMany("VenueHosting.Module.Attendee.Domain.Attendee.ValueObjects.ReservationId", "ReservationIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AttendeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Id");

                            b1.HasKey("Id");

                            b1.HasIndex("AttendeeId");

                            b1.ToTable("AttendeeReservationIds", "Attendee", t =>
                                {
                                    t.Property("Id")
                                        .HasColumnName("Id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("AttendeeId");
                        });

                    b.OwnsMany("VenueHosting.Module.Attendee.Domain.Attendee.ValueObjects.VenueId", "VenueIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AttendeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Id");

                            b1.HasKey("Id");

                            b1.HasIndex("AttendeeId");

                            b1.ToTable("AttendeeVenueIds", "Attendee", t =>
                                {
                                    t.Property("Id")
                                        .HasColumnName("Id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("AttendeeId");
                        });

                    b.OwnsMany("VenueHosting.Module.Attendee.Domain.AttendeeReview.ValueObjects.AttendeeReviewId", "AttendeeReviewIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("AttendeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("AttendeeReviewId");

                            b1.HasKey("Id");

                            b1.HasIndex("AttendeeId");

                            b1.ToTable("AttendeeReviewIds", "Attendee");

                            b1.WithOwner()
                                .HasForeignKey("AttendeeId");
                        });

                    b.Navigation("AttendeeReviewIds");

                    b.Navigation("BillIds");

                    b.Navigation("ReservationIds");

                    b.Navigation("VenueIds");
                });
#pragma warning restore 612, 618
        }
    }
}
