// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VenueHosting.Module.Lessee.Infrastructure.Persistence;

#nullable disable

namespace VenueHosting.Module.Lessee.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LesseeApplicationDbContext))]
    [Migration("20230519111255_SplitSetUp")]
    partial class SplitSetUp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Lessee")
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VenueHosting.Module.Lessee.Domain.Lessee.Lessee", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Lessees", "Lessee");
                });

            modelBuilder.Entity("VenueHosting.Module.Lessee.Domain.LesseeReview.LesseeReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Comment");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedDateTime");

                    b.Property<Guid>("LesseeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("RatingGiven")
                        .HasColumnType("real")
                        .HasColumnName("RatingGiven");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("LesseeReviews", "Lessee");
                });

            modelBuilder.Entity("VenueHosting.Module.Lessee.Domain.Lessee.Lessee", b =>
                {
                    b.OwnsMany("VenueHosting.Module.Lessee.Domain.Lessee.ValueObjects.VenueId", "VenueIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("LesseeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Id");

                            b1.HasKey("Id");

                            b1.HasIndex("LesseeId");

                            b1.ToTable("VenueId", "Lessee", t =>
                                {
                                    t.Property("Id")
                                        .HasColumnName("Id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("LesseeId");
                        });

                    b.OwnsMany("VenueHosting.Module.Lessee.Domain.LesseeReview.ValueObjects.LesseeReviewId", "LesseeReviewIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("LesseeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("Id");

                            b1.HasKey("Id");

                            b1.HasIndex("LesseeId");

                            b1.ToTable("LesseeReviewIds", "Lessee", t =>
                                {
                                    t.Property("Id")
                                        .HasColumnName("Id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("LesseeId");
                        });

                    b.Navigation("LesseeReviewIds");

                    b.Navigation("VenueIds");
                });
#pragma warning restore 612, 618
        }
    }
}
